server:
  port: 8089
  servlet:
    context-path: "/ecomm-stock/"

spring:
  application:
    name: ecommerce-stock-service
  datasource:
    url: jdbc:mysql://localhost:3309/stocks?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: joel
    password: docker
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    locations: classpath:db/migration,classpath:db/testdb
    enabled: true
    baseline-on-migrate: true


logging:
  level:
    com.stock: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO